### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by Foxiallis** [Senior-S/JustLeveling-Fork#10]
Steps to replicate:

1. Don't have enough levels to craft something (let's say gold block)
2. Hold left click and drag gold ingots across the crafting (to equally spread them). Make sure that some items would be left in your hand (so, for the gold block example, you would have to have an amount indivisible by 9)
3. You would be thrown off the crafting grid with the error that you don't have enough level
4. Your (in this example) gold bars would multiply by a random amount - sometimes just by the amount left in your hand, and sometimes even by twice the amount you originally put in

Tested on a multiplayer server on JLF 1.1.4

**Comment by Senior-S** [comment]
Hi, this error is already known and is caused by other mods changing the crafting table behavior, the only fix is set `closeCraftingMenu` to false in the common config
