### ISSUE TITLE
Basic configuration for mods

### ISSUE THREAD

**Issue by Foxiallis** [Senior-S/JustLeveling-Fork#13]
Hi!
Very happy about the way you work with the mod. It received regular updates and fixes for issues that I created, and it's been a blast playing with it on the server.
So, I wanna give back - I've configured the requirements based on your vanilla values for more than 60 mods that we've been using in the modpack. If you wish - I can send the config file to you to include some preconfigured values tested on multiplayer for all these mods.

**Comment by Senior-S** [comment]
Hi, thanks for your support, I appreciate your effort on this, in the discord server I already have a channel to share already made config files along kubejs scripts, feel free to join and share the files there ^^
Discord invite link: https://discord.gg/6c6cDU2mKj
Channel link: https://discordapp.com/channels/1266498719130583050/1269494389605142538
