### ISSUE TITLE
Player can't enter the server after lock item update

### ISSUE THREAD

**Issue by Foxiallis** [Senior-S/JustLeveling-Fork#14]
[message.txt](https://github.com/user-attachments/files/17149968/message.txt)

The message on the server is attached in the txt file.

A player can't connect to the server, and I think it's because of JLFork. One of two things caused this:
1. I changed a config, upping some requirements for curios. Maybe this player is wearing them and doesn't have enough stats after the update, causing them to be unable to join
2. I updated to version 1.1.5

**Comment by Foxiallis** [comment]
Update: It indeed was caused by changing the requirements for items. So, here are the steps to reproduce:

1. Equip a curio item with a requirement that you fulfill (e.g. golden ring that requires Luck 4)
2. Quit the game
3. Change the server config locked items file to change the required level of that curio to one that player does not fulfill
4. Restart the server
5. When player tries to enter, the error message posted above will appear in the console

To fix this, I temporarily removed locked items file, let the player remove all their curios, and then added the config file again.

**Comment by Senior-S** [comment]
I updated the DLL at https://github.com/Senior-S/JustLeveling-Fork/releases/tag/1.1.5
Please download that version, it fixes this issue.
