### ISSUE TITLE
Crashing on Startup and In game both latest Versions

### ISSUE THREAD

**Issue by SHXRKIEgg** [Senior-S/JustLeveling-Fork#18]
Crashed Loading on Latest JLFork-1.1.6-Fixed 1.20.1
[latest.log](https://github.com/user-attachments/files/17443780/latest.log)

Crashed joining world on JLFork-1.1.6 1.20.1 (Might not be fixed in the latest? so just posting here to make sure)
[crash-2024-10-19_14.49.30-client.txt](https://github.com/user-attachments/files/17443777/crash-2024-10-19_14.49.30-client.txt)

**Comment by Senior-S** [comment]
Hi, it just have been fixed on 1.1.6-Fix:
https://github.com/Senior-S/JustLeveling-Fork/releases/tag/1.1.6

**Comment by SHXRKIEgg** [comment]
As I said, it is also crashing on that version
