### ISSUE TITLE
Crashing on Latest JLFork-1.1.6-Fixed 1.20.1

### ISSUE THREAD

**Issue by SHXRKIEgg** [Senior-S/JustLeveling-Fork#19]
#18 Seems like it was ignored.
Crashing on latest Fixed version (JLFork-1.1.6-Fixed 1.20.1) on startup, no crash but the log tells you it crashes
[latest.log](https://github.com/user-attachments/files/17444404/latest.log)

**Comment by Senior-S** [comment]
Hi, sorry for the issue, this was a issue that didn't appear while testing on the dev environment, it have been fixed now on the 1.1.6-Fix2.
Github link: https://github.com/Senior-S/JustLeveling-Fork/releases/tag/1.1.6
Modrinth link: https://modrinth.com/mod/justleveling-fork/version/1.1.6-Fix
The CurseForge version is still under review.

Feel free to test it and close the issue if it have been resolved.
