### ISSUE TITLE
Feature Request: Kubejs

### ISSUE THREAD

**Issue by Darklord2996** [Senior-S/JustLeveling-Fork#2]
Hey man love how you de-compiled to get the source must've been hard, anyway do you plan for Kubejs support? i would love to hook into the events with it specifically titles or the skills using kube, would allow me to do a lot since i could make certain stuff trigger through it. if it already exists do inform me! There wasn't a format for issues so i hope you don't mind!

**Comment by Darklord2996** [comment]
Cheers i joined the discord when i made the issue would you like me to just close this and put it on your suggestion form on there instead?

**Comment by Senior-S** [comment]
Nah, I'll keep this issue open as well until I release the update with support for KubeJS.

**Comment by Senior-S** [comment]
https://github.com/Senior-S/JustLeveling-Fork/releases/tag/1.1.1
