### ISSUE TITLE
Doesn't work with Better ModList (Mod Menu for Forge)

### ISSUE THREAD

**Issue by leyxcx** [Senior-S/JustLeveling-Fork#23]
When trying to edit the config this error pops up, (sorry for the phone picture instead of a screenshot, windows is crap) 
![IMG_3704](https://github.com/user-attachments/assets/88f09658-07de-40ef-ab29-fb40a15abf99)

**Comment by Senior-S** [comment]
You need to downgrade YetAnotherConfigLib to the version 3.4.2

You can download it here: https://modrinth.com/mod/yacl/version/3.4.2+1.20.1-forge
![image](https://github.com/user-attachments/assets/24bf97a6-a435-4751-b3b9-63f291f1670e)

**Comment by leyxcx** [comment]
sorry I'm dumb and  didn't see that, thank you for the help :)
