### ISSUE TITLE
Current Health resets after rejoining

### ISSUE THREAD

**Issue by ZLGaming** [Senior-S/JustLeveling-Fork#24]
The player's current health does not save after rejoining the world
I have a increased max health, healed myself to max and then rejoined to find it back to 20 health

**Comment by dobscha777** [comment]
Download Max Health Fix mod:
https://www.curseforge.com/minecraft/mc-mods/max-health-fix

**Comment by ZLGaming** [comment]
Oh that fixed it, thank you
