### ISSUE TITLE
Level Up Glitch

### ISSUE THREAD

**Issue by dobscha777** [Senior-S/JustLeveling-Fork#25]
When you have enough experience points to level up a skill but decide to use them to enchant an item before actually investing in the skill, the game still allows you to upgrade that skill. In other words, even without enough points left after enchanting, you can still enhance the skill. 

Here's a video showing the bug:

https://www.youtube.com/watch?v=c-mkh21mAcw

Even with 11 levels, I still be able to upgrade the skill that requires 26 levels.

**Comment by Senior-S** [comment]
I added a fix for this on 1.1.8, feel free to report it if the issue still persists.
https://modrinth.com/mod/justleveling-fork/versions
Still under review on Curseforge.
