### ISSUE TITLE
Config to disable certain skills

### ISSUE THREAD

**Issue by gobies21** [Senior-S/JustLeveling-Fork#27]
theres some skills that i would like to remove from the skill menu
![image](https://github.com/user-attachments/assets/1a741e19-193e-4d3c-855b-7633bd1a539c)

**Comment by Darklord2996** [comment]
if you set the level requirement in the config to -1 that all you need to do
in your config folder find "minecraft\config\JLFork\justleveling-fork.common.json5"
e.g line 288 is what you need to change 32 to -1 to "disable" the skill
`catEyesRequiredLevel: 32,`

**Comment by gobies21** [comment]
oh i was not aware of this thank you
