### ISSUE TITLE
tri incompatibility between Justleveling fork - nukecraft - better combat

### ISSUE THREAD

**Issue by VxN-Drev** [Senior-S/JustLeveling-Fork#5]
crash straight to desktop when using both nukacraft (note: not there requirements) & better combat with you mod, I'm posting here because deleting     "MixTargetFinder",  from the mix-ins stops the crash & seems to allow for normal play (no long term testing)

**Comment by Senior-S** [comment]
Hi, can you check if this issue is fixed on version 1.1.7?
