### ISSUE TITLE
New KubeJS event crashes game

### ISSUE THREAD

**Issue by SHXRKIEgg** [Senior-S/JustLeveling-Fork#6]
Updated to latest and it crashes cause if the new KubeJS event
[crash-2024-09-18_01.50.43-client.txt](https://github.com/user-attachments/files/17032943/crash-2024-09-18_01.50.43-client.txt)

**Comment by Senior-S** [comment]
Hi, sorry for the issue.
You can download the fixed version here:
https://github.com/Senior-S/JustLeveling-Fork/releases/tag/1.1.3-Fix
