### ISSUE TITLE
What does Curious API do for this mod ?

### ISSUE THREAD

**Issue by Beez3-A** [Senior-S/JustLeveling-Fork#9]
Hello good day,

awesome mod really cool! 

just wondering why this mod need the curious api...
like do we need it or can this mod run without it? 

Reason i ask is cause I use forge but with connector and I use trinkets instead of forge because of specific mod that only uses trinkets.

So I'm wondering what we need curious for, for your mod what does it do and do I need it ect.

sorry I'm a noob at this

**Comment by Senior-S** [comment]
Hi Curios is required to lock the trinkets that are added through the curios api like [artifacts](https://www.curseforge.com/minecraft/mc-mods/artifacts)

**Comment by Beez3-A** [comment]
I don't need this mod (artifacts ) though, right ? 

We can just use your mod correct ?

When using artifacts could we just use the fabric version with Trinkets API ?

**Comment by Senior-S** [comment]
Yes, it does work without the Curios API.
